# Generated by Django 4.0.6 on 2022-07-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('squad', models.CharField(choices=[('i', 'infraestrutura'), ('v', 'vendas'), ('t', 'tech'), ('j', 'juridico')], max_length=1)),
                ('descricao', models.TextField(max_length=200)),
                ('feito', models.BooleanField(default=False)),
            ],
        ),
    ]
