# Generated by Django 4.0.6 on 2022-07-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('squad', models.CharField(choices=[('infra', 'infraestrutura'), ('vendas', 'vendas'), ('tech', 'tech'), ('juridico', 'juridico')], max_length=10)),
                ('descricao', models.TextField(max_length=200)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
